version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - pfichtner
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - "> 3.5.9"
    - "< 3.6"
